name: IONOS.space

on: [push]

jobs:
  ionos-space:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Get Ionos Project data
        uses: buildwith-ionos/retrieve-project-info-action@v0.1.3
        id: project
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          project: aa182553-9dc3-40c1-ab49-58a8fb8c9f8f
          service-host: api-eu.ionos.space
      - name: Setup Node.js 12.16.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.x
      - name: Prepare Project build environment
        run: |
          npm install --global yarn
          yarn install --frozen-lockfile
      - name: Build Node project
        run: yarn build
        env:
          SITE_URL: ${{ steps.project.outputs.site-url }}
          CI: true
      - name: Deploy to IONOS
        uses: buildwith-ionos/deploy-to-ionos-action@v0.1.3
        with:
          dist-folder: dist
          service-host: api-eu.ionos.space
          project: aa182553-9dc3-40c1-ab49-58a8fb8c9f8f
          remote-host: ${{ steps.project.outputs.remote-host }}
          api-key: ${{ secrets.IONOS_API_KEY }}
